import React, { useState, useEffect } from "react";
import Head from "next/head";
import { Box, IconButton } from "@mui/material";
import CampaignDetailsImg from "../../../components/CampaignDetailsImg";
import MainLayout from "../../../layouts/MainLayout";
import { Typography } from "@mui/material";
import CampaignDetailsInfo from "../../../components/CampaignDetailsInfo";
import { useRouter } from "next/router";
import { useAppContext } from "../../../context";
import Loader from "../../../components/Loader";
import TableDonators from "../../../components/TableDonators";
import OngDetailsImg from "../../../components/OngDetailsImg";

const OngDetails = () => {
  const [loading, setLoading] = useState(false);
  const [donators, setDonators] = useState([]);
  const [ongs, setOngs] = useState([]);

  const router = useRouter();
  const id = router.query.id;

  const { getDonatorsOng, contract, address, getOngs } = useAppContext();

  const fetchOngs = async () => {
    setLoading(true);
    const data = await getOngs();
    setOngs(data);
    setLoading(false);
  };

  useEffect(() => {
    if (contract) fetchOngs();
  }, [address, contract]);

  const fetchDonators = async () => {
    const data = await getDonatorsOng(id);

    setDonators(data);
    console.log("donators", donators);
  };

  useEffect(() => {
    if (contract) fetchDonators();
  }, [contract, address]);

  console.log("aiciiiiiiiiii");

  return (
    <>
      <Head>
        <title>Ong Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            flexDirection: "column",
          }}
        >
          {loading && <Loader />}
          <Box
            sx={{
              display: "flex",
              justifyContent: "space-around",
              alignItems: "center",
              flexDirection: "row",
              ml: "8rem",
              mr: "5rem",
              mt: "3rem",
              width: "80%",
            }}
          >
            <OngDetailsImg />

            <CampaignDetailsInfo />
          </Box>

          <Box
            sx={{
              ml: "8rem",
              mr: "5rem",
              mt: "3rem",

              width: "80%",
            }}
          >
            <Box
              sx={{
                bgcolor: "textBg.main",
                borderRadius: "15px",
                width: "100%",
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                flexDirection: "column",
              }}
            >
              <Box sx={{ mb: "1rem", mt: "1rem" }}>
                <Typography
                  variant="h4"
                  align="left"
                  sx={{ fontWeight: "bold", fontSize: 25 }}
                >
                  Story
                </Typography>
              </Box>
              <Box sx={{ pb: "2rem" }}>
                <Typography variant="h4" align="left" sx={{ fontSize: 18 }}>
                  {ongs[id]?.description}
                </Typography>
              </Box>
            </Box>
          </Box>

          <Box
            sx={{
              ml: "8rem",
              mr: "5rem",
              mt: "3rem",

              width: "80%",
            }}
          >
            <Box
              sx={{
                bgcolor: "textBg.main",
                borderRadius: "15px",
                width: "100%",
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                flexDirection: "column",
              }}
            >
              <Box sx={{ mb: "1rem", mt: "1rem" }}>
                <Typography
                  variant="h4"
                  align="left"
                  sx={{ fontWeight: "bold", fontSize: 25 }}
                >
                  Donators
                </Typography>
              </Box>
              <Box sx={{ pb: "2rem" }}>
                {donators.length > 0 ? (
                  donators.map((donator, i) => (
                    <Box key={i}>
                      {" "}
                      {donator[0]} {donator[3]}
                    </Box>
                  ))
                ) : (
                  <Box> No donators yet </Box>
                )}
              </Box>
              <TableDonators donators={donators} />
            </Box>
          </Box>
        </Box>
      </MainLayout>
    </>
  );
};

export default OngDetails;
