import React, { useState } from "react";
import Head from "next/head";
import {
  Box,
  IconButton,
  Container,
  InputAdornment,
  Typography,
} from "@mui/material";
import logo from "../assets/logo.png";
import PetsOutlinedIcon from "@mui/icons-material/PetsOutlined";
import ButtonConnect from "../components/ButtonConnect";
import { useRouter } from "next/router";
import TableHome from "../components/TableHome";

const HomePage = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Box
        sx={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          flexDirection: "column",
          width: "100%",
        }}
      >
        <Box
          sx={{
            display: "flex",
            alignItems: "flex-start",
            flexDirection: "column",
            width: "95%",
            mt: "1rem",
          }}
        >
          <IconButton onClick={() => router.push("/")}>
            <img src={logo.src} alt="logo" width="80px" height="80px" />
          </IconButton>
        </Box>

        <Box
          sx={{
            bgcolor: "textBg.main",
            height: "5rem",
            borderRadius: "15px",
            width: "25%",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <InputAdornment position="start">
            <PetsOutlinedIcon fontSize="medium" />
          </InputAdornment>
          <Typography
            variant="h4"
            align="center"
            sx={{ fontWeight: "bold", fontSize: 30 }}
          >
            Welcome
          </Typography>
          <InputAdornment position="end" fontSize="large">
            <PetsOutlinedIcon />
          </InputAdornment>
        </Box>

        <Box
          sx={{
            width: "90%",
            mt: "3rem",
          }}
        >
          <Container
            sx={{
              bgcolor: "containerBg.main",
              width: "80%",
              height: "600px",
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              flexDirection: "column",
            }}
          >
            <Box
              sx={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                flexDirection: "column",
              }}
            >
              <Typography
                variant="h5"
                align="center"
                sx={{
                  fontWeight: "bold",
                  fontSize: 24,
                  width: "70%",
                  color: "textBg.main",
                }}
              >
                Support animal welfare ONG and help them save and improve the
                lives of animals in need through their crowdfunding campaigns
              </Typography>

              <Box
                sx={{
                  display: "flex",
                  justifyContent: "justify-around",
                  alignItems: "center",
                  flexDirection: "row",
                  mt: "4rem",
                }}
              >
                <Box sx={{ mr: "2rem" }}>
                  <ButtonConnect
                    title={"Login"}
                    btnType="button"
                    handleClick={() => {
                      router.push("/login");
                    }}
                  />
                </Box>

                <ButtonConnect
                  title={"Register"}
                  btnType="button"
                  handleClick={() => {
                    router.push("/register");
                  }}
                />
              </Box>
              <Box sx={{ mt: "4rem" }}>
                <TableHome />
              </Box>
            </Box>
          </Container>
        </Box>
      </Box>
    </>
  );
};

export default HomePage;
