import React, { useState, useEffect } from "react";
import Head from "next/head";
import { Box, Container, InputAdornment, Typography } from "@mui/material";
import PetsOutlinedIcon from "@mui/icons-material/PetsOutlined";
import ButtonConnect from "../components/ButtonConnect";
import { useRouter } from "next/router";
import TableHome from "../components/TableHome";
import { useAppContext } from "../context";

const HomePage = () => {
  const router = useRouter();
  const [statistics, setStatistics] = useState([]);
  const { address, contract, getCampaignsStatistics } = useAppContext();

  const fetchStatistics = async () => {
    const data = await getCampaignsStatistics();
    console.log("data", data);
    setStatistics(data);
  };
  useEffect(() => {
    fetchStatistics();
  }, []);

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Box
        sx={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          flexDirection: "column",
          width: "100%",
        }}
      >
        <Box
          sx={{
            bgcolor: "textBg.main",
            height: "5rem",
            borderRadius: "15px",
            width: "25rem",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            mt: "3rem",
            "@media(max-width: 800px)": {
              width: "20rem",
            },
            "@media(max-width: 350px)": {
              width: "16rem",
            },
          }}
        >
          <InputAdornment position="start">
            <PetsOutlinedIcon fontSize="medium" />
          </InputAdornment>
          <Typography
            variant="h4"
            align="center"
            sx={{
              fontWeight: "bold",
              fontSize: 30,
              "@media(max-width: 800px)": {
                fontSize: 25,
              },
            }}
          >
            Welcome
          </Typography>
          <InputAdornment position="end" fontSize="large">
            <PetsOutlinedIcon />
          </InputAdornment>
        </Box>

        <Box
          sx={{
            width: "90%",
            mt: "3rem",
          }}
        >
          <Container
            sx={{
              bgcolor: "containerBg.main",
              width: "80%",
              height: "600px",
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              flexDirection: "column",
              borderRadius: "15px",
              "@media(max-width: 730px)": {
                pb: "2rem",
                pt: "5rem",
                height: "100%",
              },
            }}
          >
            <Box
              sx={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                flexDirection: "column",
              }}
            >
              <Typography
                variant="h5"
                align="center"
                sx={{
                  fontWeight: "bold",
                  fontSize: 24,
                  width: "70%",
                  color: "textBg.main",
                  "@media(max-width: 730px)": {
                    fontSize: 20,
                  },
                }}
              >
                Support animal welfare ONG and help them save and improve the
                lives of animals in need through their crowdfunding campaigns
              </Typography>

              <Box
                sx={{
                  display: "flex",
                  justifyContent: "justify-around",
                  alignItems: "center",
                  flexDirection: "row",
                  mt: "4rem",
                  "@media(max-width: 430px)": {
                    display: "flex",
                    justifyContent: "center",
                    alignItems: "center",
                    flexDirection: "column",
                  },
                }}
              >
                <Box
                  sx={{
                    mr: "2rem",
                    "@media(max-width: 430px)": {
                      mr: "0rem",
                    },
                  }}
                >
                  <ButtonConnect
                    title={"Login"}
                    btnType="button"
                    handleClick={() => {
                      router.push("/login");
                    }}
                  />
                </Box>

                <ButtonConnect
                  title={"Register"}
                  btnType="button"
                  handleClick={() => {
                    router.push("/register");
                  }}
                />
              </Box>
              <Box sx={{ mt: "4rem" }}>
                <TableHome />
              </Box>
            </Box>
          </Container>
        </Box>
      </Box>
    </>
  );
};

export default HomePage;
