import React, { useState, useEffect } from "react";
import Head from "next/head";
import MainLayout from "../../layouts/MainLayout";
import { useAppContext } from "../../context";
import DisplayOngs from "../../components/DisplayOngs";

const Ongs = () => {
  const [loading, setLoading] = useState(false);
  const [ongs, setOngs] = useState([]);

  const { address, contract, getOngs } = useAppContext();

  const fetchOngs = async () => {
    setLoading(true);
    const data = await getOngs();
    setOngs(data);
    setLoading(false);
  };

  useEffect(() => {
    if (contract) fetchOngs();
  }, [address, contract]);

  return (
    <>
      <Head>
        <title>Ongs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <DisplayOngs title="All ONGs" loading={loading} ongs={ongs} />
      </MainLayout>
    </>
  );
};

export default Ongs;
