import React from "react";
import Head from "next/head";
import BoxCount from "../components/BoxCount";
import FundCard from "../components/FundCard";
import { Box } from "@mui/material";
import CampaignDetailsImg from "../components/CampaignDetailsImg";
import MainLayout from "../layouts/MainLayout";
import { Typography } from "@mui/material";

const CampaignDetails = () => {
  return (
    <>
      <Head>
        <title>Campaign Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <MainLayout>
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            flexDirection: "column",
          }}
        >
          <Box
            sx={{
              display: "flex",
              justifyContent: "space-around",
              alignItems: "center",
              flexDirection: "row",
              ml: "8rem",
              mr: "5rem",
              mt: "3rem",
              width: "80%",
            }}
          >
            <CampaignDetailsImg />
            <Box
              sx={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                flexDirection: "column",
                width: "70%",
              }}
            >
              <Box
                sx={{
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  flexDirection: "column",
                }}
              >
                <Typography
                  variant="h4"
                  align="center"
                  sx={{ fontWeight: "bold", fontSize: 25 }}
                >
                  Title
                </Typography>
              </Box>
            </Box>
          </Box>
          <Box sx={{ ml: "8rem", mr: "5rem", mt: "3rem", width: "80%" }}>
            <Typography
              variant="h4"
              align="left"
              sx={{ fontWeight: "bold", fontSize: 25 }}
            >
              Story
            </Typography>
            <Typography variant="h4" align="left" sx={{ fontSize: 18 }}>
              descrierea
            </Typography>
          </Box>
          <Box sx={{ ml: "8rem", mr: "5rem", mt: "3rem", width: "80%" }}>
            Tabel
          </Box>
        </Box>
      </MainLayout>
    </>
  );
};

export default CampaignDetails;
