import React, { useState, useEffect } from "react";
import Head from "next/head";
import MainLayout from "../layouts/MainLayout";
import CampaignCard from "../components/CampaignCard";
import { useAppContext } from "../context";
import DisplayCampaigns from "../components/DisplayCampaigns";

const Campaigns = () => {
  const [loading, setLoading] = useState(false);
  const [campaigns, setCampaigns] = useState([]);

  const { address, contract, getCampaigns } = useAppContext();

  const fetchCampaigns = async () => {
    setLoading(true);
    const data = await getCampaigns();
    console.log("data", data);
    setCampaigns(data);
    setLoading(false);
  };

  useEffect(() => {
    if (contract) {
      console.log("contract");
      fetchCampaigns();
      console.log("aici");
    }
  }, [address, contract]);

  return (
    <>
      <Head>
        <title>Campaigns</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <DisplayCampaigns
          title="All campaigns"
          loading={loading}
          campaigns={campaigns}
        />
        {/* <CampaignCard /> */}
      </MainLayout>
    </>
  );
};

export default Campaigns;
