import React from "react";
import Head from "next/head";

const Campaigns = () => {
  return (
    <>
      <Head>
        <title>Campaigns</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>Campaigns</div>
    </>
  );
};

export default Campaigns;
