import React from "react";
import Head from "next/head";
import MainLayout from "../layouts/MainLayout";
import CampaignCard from "../components/CampaignCard";

const Campaigns = () => {
  return (
    <>
      <Head>
        <title>Campaigns</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <MainLayout>
        <CampaignCard />
      </MainLayout>
    </>
  );
};

export default Campaigns;
