import React from "react";
import Head from "next/head";
import BoxCount from "../components/BoxCount";

const CampaignDetails = () => {
  return (
    <>
      <Head>
        <title>Campaign Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>Campaign Details</div>
      <BoxCount />
    </>
  );
};

export default CampaignDetails;
