import React from "react";
import Head from "next/head";
import MainLayout from "../layouts/MainLayout";
import { useRouter } from "next/router";
import { useAppContext } from "../context";
import { useEffect, useState } from "react";
import DisplayCampaigns from "../components/DisplayCampaigns";
import { truncate } from "../utils/functions";
import Loader from "../components/Loader";

const CampaignsByOng = () => {
  const router = useRouter();
  const { id, ongs, ongName } = router.query;
  console.log(id, "id", ongs, "ongs");

  const [loading, setLoading] = useState(false);
  const [campaigns, setCampaigns] = useState([]);

  const { address, contract, getCampaignsByOwner } = useAppContext();

  const fetchCampaignsByOng = async () => {
    setLoading(true);
    const data = await getCampaignsByOwner(ongs);
    setCampaigns(data);
    // router.push("/ongs");
    setLoading(false);
  };

  useEffect(() => {
    if (contract) fetchCampaignsByOng();
  }, [contract, address]);

  return (
    <>
      <Head>
        <title>RaiseAPet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        {loading && <Loader />}
        <DisplayCampaigns
          campaigns={campaigns}
          title={`Campaigns by ${ongName}`}
          loading={loading}
        />
      </MainLayout>
    </>
  );
};

export default CampaignsByOng;
