import React from "react";
import Head from "next/head";

const CauseDetails = () => {
  return (
    <>
      <Head>
        <title>Cause Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>Cause Details</div>
    </>
  );
};

export default CauseDetails;
