import React from "react";
import Head from "next/head";

const Chat = () => {
  return (
    <>
      <Head>
        <title>Chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>Settings</div>
    </>
  );
};

export default Chat;
