import React from "react";
import MainLayout from "../layouts/MainLayout";
import Head from "next/head";

function ForgotPassword() {
  return (
    <>
      <Head>
        <title>Forget Password</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout></MainLayout>
    </>
  );
}

export default ForgotPassword;
