import Head from "next/head";
import { Typography, Box } from "@mui/material";
import ButtonConnect from "@/components/ButtonConnect";
import LoginLayout from "@/layouts/LoginRegisterLayout";
import SelectUserType from "@/components/SelectUserType";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Crowdfunding</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            flexDirection: "column",
          }}
        >
          <Box
            sx={{
              bgcolor: "#3b3247",
              height: "5rem",
              borderRadius: "15px",
              width: "25%",
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              mt: "5rem",
            }}
          >
            <Typography
              variant="h4"
              align="center"
              sx={{ fontWeight: "bold", fontSize: 30 }}
            >
              Login
            </Typography>
          </Box>
          <LoginLayout>
            <SelectUserType
              showMessage={true}
              title={"Connect"}
              ifRegister={false}
            />
          </LoginLayout>

          <ButtonConnect
            title="Next"
            handleClick={() => {
              router.push("/create-campaign");
            }}
          />
          <ButtonConnect
            title="Register"
            handleClick={() => {
              router.push("/register");
            }}
          />
        </Box>
      </main>
    </>
  );
}
