import React, { useState, useEffect } from "react";
import Head from "next/head";
import MainLayout from "../layouts/MainLayout";
import { useAppContext } from "../context";
import DisplayCampaigns from "../components/DisplayCampaigns";
import { getGlobalState, useGlobalState } from "../globalState";

const Profile = () => {
  const [loading, setLoading] = useState(false);
  const [campaigns, setCampaigns] = useState([]);
  // const [type, setType] = useGlobalState("type");
  // console.log("type", type);

  const { address, contract, getUserCampaigns, getDonatedCampaigns } =
    useAppContext();

  const fetchCampaigns = async () => {
    if (typeof window !== "undefined") {
      const type = localStorage.getItem("type");

      if (type === "ONG") {
        const data = await getUserCampaigns();
        console.log("data", data, type);
        setCampaigns(data);
        setLoading(false);
      } else if (type === "Donator") {
        setLoading(true);

        const data = await getDonatedCampaigns();
        console.log("data", data, type);
        setCampaigns(data);
        setLoading(false);
      }
    }
  };

  useEffect(() => {
    if (contract) {
      const type = localStorage.getItem("type");
      fetchCampaigns();
    }
  }, [address, contract]);
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <DisplayCampaigns
          title="All campaigns"
          loading={loading}
          campaigns={campaigns}
        />
      </MainLayout>
    </>
  );
};

export default Profile;
