import React, { useState, useEffect } from "react";
import Head from "next/head";
import MainLayout from "../layouts/MainLayout";
import { useAppContext } from "../context";
import DisplayCampaigns from "../components/DisplayCampaigns";
import { set } from "mongoose";

const Profile = () => {
  const [loading, setLoading] = useState(false);
  const [campaigns, setCampaigns] = useState([]);
  const [donators, setDonators] = useState([]);

  const { address, contract, getUserCampaigns, getCampaignsByDonator } =
    useAppContext();

  const [type, setType] = useState("");

  useEffect(() => {
    fetch("api/getType").then((res) => {
      res.json().then((data) => {
        console.log("data", data);
        setType(data);
      });
    });
  }, []);

  useEffect(() => {
    const donators = JSON.parse(localStorage.getItem("donators"));
    setDonators(donators);
    const type = localStorage.getItem("type");
  }, []);

  const fetchCampaigns = async () => {
    const type = localStorage.getItem("type");
    console.log("type", type);
    if (type === "ONG") {
      setLoading(true);
      const data = await getUserCampaigns();
      setCampaigns(data);
      setLoading(false);
    }
  };

  useEffect(() => {
    if (contract) fetchCampaigns();
    const type = localStorage.getItem("type");
  }, [address, contract]);

  const fetchDonators = async () => {
    const type = localStorage.getItem("type");
    if (type === "Donator") {
      setLoading(true);
      const data = await getCampaignsByDonator(address.toLowerCase());
      setCampaigns(data);
      setLoading(false);
    }
  };

  useEffect(() => {
    if (contract) fetchDonators();
    const type = localStorage.getItem("type");
    // setType(type);
  }, [contract, address]);

  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <DisplayCampaigns
          title="All Campaigns"
          loading={loading}
          campaigns={campaigns}
        />
      </MainLayout>
    </>
  );
};

export default Profile;
