import React from "react";
import LoginLayout from "../layouts/LoginRegisterLayout";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import Head from "next/head";
import PetsOutlinedIcon from "@mui/icons-material/PetsOutlined";
import InputAdornment from "@mui/material/InputAdornment";
import UserRegister from "../components/UserRegister";
import { IconButton } from "@mui/material";
import logo from "../assets/logo.png";

const Register = () => {
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          flexDirection: "column",
        }}
      >
        {/* <Box
          sx={{
            display: "flex",
            alignItems: "flex-start",
            flexDirection: "column",
            width: "95%",
            mt: "1rem",
          }}
        >
          <IconButton onClick={() => router.push("/")}>
            <img src={logo.src} alt="logo" width="80px" height="80px" />
          </IconButton>
        </Box> */}
        <Box
          sx={{
            bgcolor: "textBg.main",
            height: "5rem",
            borderRadius: "15px",
            width: "25%",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            mt: "3rem",
          }}
        >
          <InputAdornment position="start">
            <PetsOutlinedIcon fontSize="medium" />
          </InputAdornment>
          <Typography
            variant="h4"
            align="center"
            sx={{ fontWeight: "bold", fontSize: 30 }}
          >
            Create account
          </Typography>
          <InputAdornment position="end">
            <PetsOutlinedIcon fontSize="medium" />
          </InputAdornment>
        </Box>
        <LoginLayout>
          {/* <UserRegister
            showMessage={false}
            title={"Register"}
            messageTitle={"Register"}
          /> */}
          {/* <SelectUserType
            showMessage={false}
            title={"Register"}
            ifRegister={true}
            messageTitle={"Register"}
          /> */}
          <UserRegister
            showMessage={true}
            title={"Register"}
            messageTitle={"Register"}
          />
        </LoginLayout>
      </Box>
    </>
  );
};

export default Register;
