import React from "react";
import LoginLayout from "../layouts/LoginRegisterLayout";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import Head from "next/head";
import PetsOutlinedIcon from "@mui/icons-material/PetsOutlined";
import InputAdornment from "@mui/material/InputAdornment";
import UserRegister from "../components/UserRegister";
import SwitchMode from "../components/SwitchMode";

const Register = () => {
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          flexDirection: "column",
        }}
      >
        <Box
          sx={{
            display: "flex",
            justifyContent: "flex-end",
            alignItems: "center",
            flexDirection: "row",
            width: "100%",
            height: "1rem",
            mr: "4rem",
            mt: "1rem",
            "@media(max-width: 400px)": {
              width: "100%",
              ml: "12rem",
            },
          }}
        >
          <SwitchMode />
        </Box>
        <Box
          sx={{
            bgcolor: "textBg.main",
            height: "5rem",
            borderRadius: "15px",
            width: "25%",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            mt: "3rem",
          }}
        >
          <InputAdornment position="start">
            <PetsOutlinedIcon fontSize="medium" />
          </InputAdornment>
          <Typography
            variant="h4"
            align="center"
            sx={{ fontWeight: "bold", fontSize: 30 }}
          >
            Create account
          </Typography>
          <InputAdornment position="end">
            <PetsOutlinedIcon fontSize="medium" />
          </InputAdornment>
        </Box>
        <LoginLayout>
          <UserRegister
            showMessage={true}
            title={"Register"}
            messageTitle={"Register"}
          />
        </LoginLayout>
      </Box>
    </>
  );
};

export default Register;
