import React from "react";
import Head from "next/head";
import MainLayout from "../layouts/MainLayout";
import Link from "@mui/material/Link";
import Typography from "@mui/material/Typography";

const Settings = () => {
  return (
    <>
      <Head>
        <title>Settings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <Typography
          align="center"
          sx={{
            fontWeight: "bold",
            fontSize: 16,
            mt: "4rem",
            mb: "1rem",
          }}
        >
          Change password{" "}
          <Link href="/change-password" color="#fff">
            here.
          </Link>
        </Typography>
      </MainLayout>
    </>
  );
};

Settings.auth = true;

export default Settings;
